name: Tests & Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Format with black
      run: |
        # Format the files instead of just checking
        black src/
        # Check if any changes were made
        git diff --exit-code || (echo "Code formatting needed. Run 'black src/' locally" && exit 1)
        
    - name: Run linting
      run: |
        pylint src/ --disable=C0111,C0103
        
    - name: Run tests
      run: |
        pytest tests/ -v
        
    - name: Commit formatting changes
      if: failure() && github.event_name == 'pull_request'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add src/
        git commit -m "Apply black formatting" || echo "No changes to commit"
        git push || echo "No changes to push"
